### PR TITLE
Update onboarding

### PR DESCRIPTION
**Pull request by Dkendal**
Updates read-me instructions. Now with more pictures!

### CODE REVIEW

**Comment by Dkendal** [comment]
Just an FYI that images might not appear in the rich diff for some reason so you can view the rendered readme at https://github.com/Dkendal/nextjs-shopify/tree/update-onboarding

**Review by steve8708 — APPROVED** [review]
this is great

**Comment by Dkendal** [comment]
Just want to point out this comment that I left near the end of the readme:

```
!-- This guide needs a lot more work here, clarifying how to get some basic stuff -->
<!-- working with in builder, building out product grids etc - the ./builder content -->
<!-- that's intially published is hard coded to the collections on the demo store -->
<!-- and won't work out of the box. -->
```

This change should clarify a lot of the nitty gritty of how to stitch together Shopify and Builder's configurations but there's a big section to be covered on just "building your first collection page" using builder. As it is now the first thing you're likely to see landing in the CMS is an error from next.js.

**Comment by Dkendal** [comment]
@steve8708 or @teleaziz feel free to merge whenever you want - I don't have write access :)

**Comment by steve8708** [comment]
Let's get this in for anyone who looks at this now but @teleaziz don't hesitate to stop add feedback that we can address in subsequent PRs

**Pull request merged**
